In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
%matplotlib inline

In [26]:
train = pd.read_csv('train.csv')

#fill NaNs
avg_age = np.mean(train['Age'])
train['Age'] = train['Age'].fillna(avg_age)
train['Cabin'] = train['Cabin'].fillna(False)

#normalize 'Age' and 'Fare' columns
fare_array = np.array(train['Fare'].values)
fare_array = fare_array.reshape(-1,1)
norm_fare = preprocessing.normalize(fare_array, axis=0)
train['Fare'] = norm_fare
age_array = np.array(train['Age'].values)
age_array = age_array.reshape(-1,1)
norm_age = preprocessing.normalize(age_array, axis=0)
train['Age'] = norm_age

#change 'cabin' and 'Sex' into numerical data types
train['cabin_bool'] = [(x != False) for x in train['Cabin'].values]
train['Sex'] = [(x == 'male') for x in train['Sex'].values]
print(train['Survived'].value_counts())
train.head(45)

0    549
1    342
Name: Survived, dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,cabin_bool
0,1,0,3,"Braund, Mr. Owen Harris",True,0.022735,1,0,A/5 21171,0.004103,False,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",False,0.039270,1,0,PC 17599,0.040344,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",False,0.026869,0,0,STON/O2. 3101282,0.004485,False,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",False,0.036170,1,0,113803,0.030053,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",True,0.036170,0,0,373450,0.004556,False,S,False
5,6,0,3,"Moran, Mr. James",True,0.030692,0,0,330877,0.004787,False,Q,False
6,7,0,1,"McCarthy, Mr. Timothy J",True,0.055805,0,0,17463,0.029353,E46,S,True
7,8,0,3,"Palsson, Master. Gosta Leonard",True,0.002067,3,1,349909,0.011928,False,S,False
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",False,0.027903,0,2,347742,0.006301,False,S,False
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",False,0.014468,1,0,237736,0.017019,False,C,False
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",False,0.004134,1,1,PP 9549,0.009452,G6,S,True
11,12,1,1,"Bonnell, Miss. Elizabeth",False,0.059939,0,0,113783,0.015026,C103,S,True
12,13,0,3,"Saundercock, Mr. William Henry",True,0.020669,0,0,A/5. 2151,0.004556,False,S,False
13,14,0,3,"Andersson, Mr. Anders Johan",True,0.040304,1,5,347082,0.017701,False,S,False
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",False,0.014468,0,0,350406,0.004445,False,S,False
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",False,0.056839,0,0,248706,0.009056,False,S,False
16,17,0,3,"Rice, Master. Eugene",True,0.002067,4,1,382652,0.016484,False,Q,False
17,18,1,2,"Williams, Mr. Charles Eugene",True,0.030692,0,0,244373,0.007358,False,S,False
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",False,0.032036,1,0,345763,0.010187,False,S,False
19,20,1,3,"Masselmani, Mrs. Fatima",False,0.030692,0,0,2649,0.004089,False,C,False
20,21,0,2,"Fynney, Mr. Joseph J",True,0.036170,0,0,239865,0.014715,False,S,False
21,22,1,2,"Beesley, Mr. Lawrence",True,0.035137,0,0,248698,0.007358,D56,S,True
22,23,1,3,"McGowan, Miss. Anna ""Annie""",False,0.015501,0,0,330923,0.004544,False,Q,False
23,24,1,1,"Sloper, Mr. William Thompson",True,0.028936,0,0,113788,0.020092,A6,S,True
24,25,0,3,"Palsson, Miss. Torborg Danira",False,0.008267,3,1,349909,0.011928,False,S,False
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",False,0.039270,1,5,347077,0.017764,False,S,False
26,27,0,3,"Emir, Mr. Farred Chehab",True,0.030692,0,0,2631,0.004089,False,C,False
27,28,0,1,"Fortune, Mr. Charles Alexander",True,0.019635,3,2,19950,0.148850,C23 C25 C27,S,True
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",False,0.030692,0,0,330959,0.004459,False,Q,False
29,30,0,3,"Todoroff, Mr. Lalio",True,0.030692,0,0,349216,0.004469,False,S,False
30,31,0,1,"Uruchurtu, Don. Manuel E",True,0.041337,0,0,PC 17601,0.015689,False,C,False
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",False,0.030692,1,0,PC 17569,0.082926,B78,C,True
32,33,1,3,"Glynn, Miss. Mary Agatha",False,0.030692,0,0,335677,0.004386,False,Q,False
33,34,0,2,"Wheadon, Mr. Edward H",True,0.068206,0,0,C.A. 24579,0.005943,False,S,False
34,35,0,1,"Meyer, Mr. Edgar Joseph",True,0.028936,1,0,PC 17604,0.046506,False,C,False
35,36,0,1,"Holverson, Mr. Alexander Oskar",True,0.043404,1,0,113789,0.029430,False,S,False
36,37,1,3,"Mamee, Mr. Hanna",True,0.030692,0,0,2677,0.004092,False,C,False
37,38,0,3,"Cann, Mr. Ernest Charles",True,0.021702,0,0,A./5. 2152,0.004556,False,S,False
38,39,0,3,"Vander Planke, Miss. Augusta Maria",False,0.018602,2,0,345764,0.010187,False,S,False
39,40,1,3,"Nicola-Yarred, Miss. Jamila",False,0.014468,1,0,2651,0.006362,False,C,False
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",False,0.041337,1,0,7546,0.005363,False,S,False
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",False,0.027903,1,0,11668,0.011885,False,S,False
42,43,0,3,"Kraeff, Mr. Theodor",True,0.030692,0,0,349253,0.004469,False,C,False
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",False,0.003100,1,2,SC/Paris 2123,0.023533,False,C,False
44,45,1,3,"Devaney, Miss. Margaret Delia",False,0.019635,0,0,330958,0.004459,False,Q,False

In [27]:
#define and split training variables
X = train[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'cabin_bool']]
y = train['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=20)

#instantiate model and fit data
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
prediction_test = model.predict(X_test)

#inspect results
print(metrics.accuracy_score(y_test, prediction_test))

0.8491620111731844